version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-academy-app
    restart: always
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=product
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - VN_PAY_TERMINAL_ID=${VN_PAY_TERMINAL_ID}
      - VN_PAY_SECRET_KEY=${VN_PAY_SECRET_KEY}
      - VN_PAY_PAYMENT_URL=${VN_PAY_PAYMENT_URL}
      - VN_PAY_RETURN_URL=${VN_PAY_RETURN_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: dev-academy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: