server:
  port: 8000
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/DevAcademy
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key : 89dd3a965fddb1460b64c074c928ee19f6697a168bc5ec72c336fb6df64289c4
  refresh-key : CZBpcWmn8Y6LLxLEFyUBj5battfY7nh+neuTbofnsM4=
  expriration : 28800000
  refresh-token :
    expriration : 604800000 # 7days

cloudinary:
  cloud_name: dn2m3s9k0
  api_key: 378291597432836
  api_secret: 9AuvGB1tA5cF0juYBQ5jqbo3Xwg