server:
  port: 8002
spring:
  config:
    activate:
      on-profile: product
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
  thymeleaf:
    encoding: UTF-8
    template-resolver-order: 1
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}

jwt:
  secret-key : ${JWT_SECRET_KEY}
  refresh-key : ${JWT_REFRESH_KEY}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}

vnpay:
  terminal-id: ${VN_PAY_TERMINAL_ID}
  secret-key: ${VN_PAY_SECRET_KEY}
  payment-url: ${VN_PAY_PAYMENT_URL}
  return-url: ${VN_PAY_RETURN_URL}

app:
  frontend:
    url: https://phhtruc.id.vn